parameters:
- name: homeDir
  displayName: Home Directory
  type: string
  default: /home
- name: loc
  displayName: Location to Build and Install
  type: string
  default: .local/bin
- name: bashEnv
  displayName: The bash profile or bashrc location
  type: string
  default: "~/.profile"
steps:
- bash: |
    set -e -x -o pipefail;
    mkdir -p ./${{ parameters.loc }};
    cd ./${{ parameters.loc }};
    curl -fsSLO https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2;
    curl -fsSLO https://github.com/samtools/bcftools/releases/download/1.18/bcftools-1.18.tar.bz2;
    curl -fsSLO https://github.com/samtools/htslib/releases/download/1.18/htslib-1.18.tar.bz2;
    tar -xvjf htslib-1.18.tar.bz2;
    tar -xvjf samtools-1.18.tar.bz2;
    tar -xvjf bcftools-1.18.tar.bz2;
    cd bcftools-1.18 && make;
    cd ../htslib-1.18 && make;
    cd ../samtools-1.18 && make;
    echo 'export PATH="$PATH:${{ parameters.homeDir }}/${{ parameters.loc }}/bcftools-1.18"' >> ${{ parameters.bashEnv }}
    echo 'export PATH="$PATH:${{ parameters.homeDir }}/${{ parameters.loc }}/samtools-1.18"' >> ${{ parameters.bashEnv }}
    echo 'export PATH="$PATH:${{ parameters.homeDir }}/${{ parameters.loc }}/htslib-1.18"' >> ${{ parameters.bashEnv }}
  displayName: 'install, build and add to PATH Samtools'
  workingDirectory: ${{ parameters.homeDir }}