name: xpress-bio CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_ROOT: ${{ github.workspace }}/resources/docker/app
      BUILD_WITH_SAMTOOLS: 'true'
      LOC: '.local/bin'
      SAMTOOLS_VERSION: '1.18'
    steps:
      - name: Setup HOME_DIR and BASH_ENV
        run: |
          echo 'HOME_DIR="$HOME"' >> $GITHUB_ENV
          echo 'BASH_ENV="$HOME/.profile"' >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 'install ubuntu libs'
        run: >
          sudo /bin/bash -c "
          set -e -x -o pipefail;
          apt-get -y update
          && apt-get -y install memcached
          && apt-get -y install libmemcached-tools
          && apt-get -y install bc
          && apt-get -y install liblz4-tool
          && apt-get -y install bsdmainutils
          ;"

      - name: 'install, build and add to PATH Samtools'
        if: ${{ env.BUILD_WITH_SAMTOOLS == 'true' }}
        run: |
          set -e -x -o pipefail;
          sudo apt-get -y update
          sudo apt-get -y install libcurl4-openssl-dev
          mkdir -p ./${{ env.LOC }};
          cd ./${{ env.LOC }};
          curl -fsSLO https://github.com/samtools/samtools/releases/download/${{ env.SAMTOOLS_VERSION }}/samtools-${{ env.SAMTOOLS_VERSION }}.tar.bz2;
          curl -fsSLO https://github.com/samtools/bcftools/releases/download/${{ env.SAMTOOLS_VERSION }}/bcftools-${{ env.SAMTOOLS_VERSION }}.tar.bz2;
          curl -fsSLO https://github.com/samtools/htslib/releases/download/${{ env.SAMTOOLS_VERSION }}/htslib-${{ env.SAMTOOLS_VERSION }}.tar.bz2;
          tar -xvjf htslib-${{ env.SAMTOOLS_VERSION }}.tar.bz2;
          tar -xvjf samtools-${{ env.SAMTOOLS_VERSION }}.tar.bz2;
          tar -xvjf bcftools-${{ env.SAMTOOLS_VERSION }}.tar.bz2;
          pushd bcftools-${{ env.SAMTOOLS_VERSION }} && make && popd;
          pushd htslib-${{ env.SAMTOOLS_VERSION }} && make && popd;
          pushd samtools-${{ env.SAMTOOLS_VERSION }} && make && popd;
          if ! grep -q "${{ env.HOME_DIR }}/${{ env.LOC }}/bcftools-${{ env.SAMTOOLS_VERSION }}" ${{ env.BASH_ENV }}; then
            echo 'export PATH="$PATH:${{ env.HOME_DIR }}/${{ env.LOC }}/bcftools-${{ env.SAMTOOLS_VERSION }}"' >> ${{ env.BASH_ENV }}
          fi
          if ! grep -q "${{ env.HOME_DIR }}/${{ env.LOC }}/samtools-${{ env.SAMTOOLS_VERSION }}" ${{ env.BASH_ENV }}; then
            echo 'export PATH="$PATH:${{ env.HOME_DIR }}/${{ env.LOC }}/samtools-${{ env.SAMTOOLS_VERSION }}"' >> ${{ env.BASH_ENV }}
          fi
          if ! grep -q "${{ env.HOME_DIR }}/${{ env.LOC }}/htslib-${{ env.SAMTOOLS_VERSION }}" ${{ env.BASH_ENV }}; then
            echo 'export PATH="$PATH:${{ env.HOME_DIR }}/${{ env.LOC }}/htslib-${{ env.SAMTOOLS_VERSION }}"' >> ${{ env.BASH_ENV }}
          fi
        working-directory: ${{ env.HOME_DIR }}

      - name: 'npm install and output coverage'
        run: |
          npm install
          npm run test-server-azure
        working-directory: ${{ env.PACKAGE_ROOT }}

      - name: 'Publish Code Coverage Results'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ${{ env.PACKAGE_ROOT }}/js/server/test/coverage/cobertura-coverage.xml
